### ISSUE TITLE
Nodes behaving strange on load of extension

### ISSUE THREAD

**Issue by MarkThorley** [radumg/DynaServer#14] opened 2018-11-09 09:18 UTC
## Expected Behavior

Nodes to display and execute correctly.

## Actual Behavior

Some nodes don't load correctly on the canvas.

## Steps to Reproduce the Problem

  1. Build the extension
  2. Open Dynamo
  3. Place nodes on canvas and run

## Specifications

    - Dynamo : 2.0.1
    - Operating system : Windows 10 
    - .NET :  4.5.2

![capture](https://user-images.githubusercontent.com/6421438/48253917-6fb3fe00-e400-11e8-8f33-f202326db347.PNG)

**Comment by radumg** [comment] 2018-11-19 18:59
closing for now as can't reproduce.

**Closed by radumg** 2018-11-19 18:59 UTC
Labels: bug, question
